# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CTLove' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CTLove

  target 'CTLoveTests' do
    inherit! :search_paths
    # Pods for testing

#json
pod 'JSONModel','~>1.1'
#autolayout
pod 'PureLayout'#,'2.0.6'
pod 'UIView+FDCollapsibleConstraints'
pod 'Masonry'

#block
pod 'BlocksKit'#,'2.2.5'

#network
pod 'AFNetworking','2.6.3'

#Core Data
#pod 'MagicalRecord', '~> 2.3.2'

#decompression
#pod 'ZipArchive'#,'1.4.0'

#刷新
pod 'SDWebImage'#,'3.7.2'
# pod 'SDWebImage', :subspecs => ['WebP']#,'0.4.3'
pod 'SVPullToRefresh'#,'0.4.1'
pod 'MBProgressHUD'#,'0.9.1'
pod 'Toast'#,'2.4'

#图片库
pod 'pop'
#pod 'libwebp', :git => 'git@iosgitlab.com:iOSPods/libwebp.git', :tag => '0.5.1'
#pod 'FLAnimatedImage', :git => 'git@iosgitlab.com:iOSPods/FLAnimatedImage.git', :tag => 'p1.0.12'
#pod 'SDWebImage/FLAnimation', :git => 'git@iosgitlab.com:iOSPods/SDWebImage.git', :tag => 'p3.8.2'

#图形
pod 'iCarousel'#,'1.8.1'
#pod 'libqrencode', :git => 'git@iosgitlab.com:iOSPods/libqrencode.git', :tag => '3.4.2'
#pod 'TZImagePickerController', :git => "https://github.com/prettychaoyao/TZImagePickerController.git"
#log
#pod 'CocoaLumberjack'#,'2.0.0'

#other
pod 'MSWeakTimer', '~> 1.1.0'

#rac
pod 'ReactiveCocoa', '~>2.5'

#view model
pod 'Nimbus/Core', '~> 1.3.0'
pod 'Nimbus/Interapp', '~> 1.3.0'
pod 'Nimbus/Models', '~> 1.3.0'

  end

  target 'CTLoveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
